# Generated by Django 3.2.4 on 2023-10-18 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('idEtiqueta', models.AutoField(db_column='idEtiqueta', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=20)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Lista_tareas',
            fields=[
                ('idLista', models.AutoField(db_column='idLista', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=45)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=200)),
                ('fk_Usuario', models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Lista_tareas',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('idTarea', models.AutoField(db_column='idTarea', primary_key=True, serialize=False)),
                ('Titulo', models.CharField(db_column='Titulo', default='Titulo', max_length=50)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=200)),
                ('Fecha_creacion', models.DateField(db_column='Fecha_creacion', default='2000-01-01')),
                ('Fecha_vencimiento', models.DateField(db_column='Fecha_vencimiento', default='2000-01-01')),
                ('Status', models.CharField(db_column='Status', default='Pendiente', max_length=15)),
                ('Prioridad', models.CharField(db_column='Prioridad', default='Baja', max_length=10)),
                ('fk_Usuario', models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='Tareas_has_etiquetas',
            fields=[
                ('idTareas_has_etiquetas', models.AutoField(db_column='idTareas_has_etiquetas', default=1, primary_key=True, serialize=False)),
                ('fk_Etiqueta', models.ForeignKey(db_column='fk_Etiqueta', on_delete=django.db.models.deletion.CASCADE, to='api.etiquetas')),
                ('fk_Tarea', models.ForeignKey(db_column='fk_Tarea', on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
            options={
                'db_table': 'Tareas_has_etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Listas_has_tareas',
            fields=[
                ('idListas_has_tareas', models.AutoField(db_column='idListas_has_tareas', default=1, primary_key=True, serialize=False)),
                ('fk_Lista', models.ForeignKey(db_column='fk_Lista', on_delete=django.db.models.deletion.CASCADE, to='api.lista_tareas')),
                ('fk_Tarea', models.ForeignKey(db_column='fk_Tarea', on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
            options={
                'db_table': 'Listas_has_tareas',
            },
        ),
    ]
