# Generated by Django 3.2.4 on 2023-10-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.IntegerField(db_column='idAlumno', primary_key=True, serialize=False)),
                ('nameAlumno', models.CharField(db_column='nameAlumno', max_length=100)),
            ],
            options={
                'db_table': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('idEtiqueta', models.AutoField(db_column='idEtiqueta', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=20)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(db_column='idGenero', primary_key=True, serialize=False)),
                ('tipoGenero', models.TextField(db_column='tipoGenero')),
            ],
            options={
                'db_table': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Lista_tareas',
            fields=[
                ('idLista', models.AutoField(db_column='idLista', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=45)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=200)),
            ],
            options={
                'db_table': 'Lista_tareas',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('idTarea', models.AutoField(db_column='idTarea', primary_key=True, serialize=False)),
                ('Titulo', models.CharField(db_column='Titulo', default='Titulo', max_length=50)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=200)),
                ('Fecha_creacion', models.DateField(db_column='Fecha_creacion', default='2000-01-01')),
                ('Fecha_vencimiento', models.DateField(db_column='Fecha_vencimiento', default='2000-01-01')),
                ('Status', models.CharField(db_column='Status', default='Pendiente', max_length=15)),
                ('Prioridad', models.CharField(db_column='Prioridad', default='Baja', max_length=10)),
            ],
            options={
                'db_table': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='nombre', max_length=45)),
                ('ApellidoP', models.CharField(db_column='ApellidoP', default='apellidop', max_length=45)),
                ('ApellidoM', models.CharField(db_column='ApellidoM', default='apellidom', max_length=45)),
                ('Fecha_nacimiento', models.DateField(db_column='Fecha_nacimiento', default='2000/01/01')),
                ('Telefono', models.IntegerField(db_column='Telefono', default=0)),
                ('Correo', models.EmailField(db_column='Correo', default='algo@algo.algo', max_length=50)),
                ('Contrasena', models.CharField(db_column='Contrasena', default='contra123', max_length=64)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Tareas_has_etiquetas',
            fields=[
                ('idTareas_has_etiquetas', models.AutoField(db_column='idTareas_has_etiquetas', default=1, primary_key=True, serialize=False)),
                ('fk_Etiqueta', models.ForeignKey(db_column='fk_Etiqueta', on_delete=django.db.models.deletion.CASCADE, to='api.etiquetas')),
                ('fk_Tarea', models.ForeignKey(db_column='fk_Tarea', on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
            options={
                'db_table': 'Tareas_has_etiquetas',
            },
        ),
        migrations.AddField(
            model_name='tareas',
            name='fk_Usuario',
            field=models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
        migrations.CreateModel(
            name='Listas_has_tareas',
            fields=[
                ('idListas_has_tareas', models.AutoField(db_column='idListas_has_tareas', default=1, primary_key=True, serialize=False)),
                ('fk_Lista', models.ForeignKey(db_column='fk_Lista', on_delete=django.db.models.deletion.CASCADE, to='api.lista_tareas')),
                ('fk_Tarea', models.ForeignKey(db_column='fk_Tarea', on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
            options={
                'db_table': 'Listas_has_tareas',
            },
        ),
        migrations.AddField(
            model_name='lista_tareas',
            name='fk_Usuario',
            field=models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
        migrations.CreateModel(
            name='alumno_has_genero',
            fields=[
                ('idalumno_has_genero', models.AutoField(db_column='idalumno_has_genero', default=1, primary_key=True, serialize=False)),
                ('fk_alumno', models.ForeignKey(db_column='fk_alumno', on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('fk_genero', models.ForeignKey(db_column='fk_genero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
            ],
            options={
                'db_table': 'alumno_has_genero',
            },
        ),
    ]
