# Generated by Django 3.2.4 on 2023-10-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
               "CREATE UNIQUE INDEX auth_user_email_idx ON auth_user (email);",
               "DROP INDEX auth_user_email_idx;"
           ),
    ]
