# Generated by Django 3.2.4 on 2023-12-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta_calidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca_temporal', models.TextField(db_column='Marca temporal', default='Marca temporal', max_length=200)),
                ('Pregunta1', models.TextField(db_column='Satisfaccion de usabilidad', default='pregunta1', max_length=200)),
                ('Pregunta2', models.TextField(db_column='Frecuencia de uso', default='pregunta2', max_length=200)),
                ('Pregunta3', models.TextField(db_column='Caracteristica mas util', default='pregunta3', max_length=200)),
                ('Pregunta4', models.TextField(db_column='Caracteristica a mejorar', default='pregunta4', max_length=200)),
                ('Pregunta5', models.TextField(db_column='La recomendarias', default='pregunta5', max_length=200)),
                ('Pregunta6', models.TextField(db_column='Velocidad y rendimiento', default='pregunta6', max_length=200)),
                ('Pregunta7', models.TextField(db_column='Servicio de FAQ', default='pregunta7', max_length=200)),
            ],
            options={
                'db_table': 'Encuesta_calidad',
            },
        ),
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('idEtiqueta', models.AutoField(db_column='idEtiqueta', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=20)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Lista_tareas',
            fields=[
                ('idLista', models.AutoField(db_column='idLista', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', default='Nombre', max_length=45)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=200)),
                ('fk_Usuario', models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Lista_tareas',
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('idPrioridad', models.AutoField(db_column='idPrioridad', primary_key=True, serialize=False)),
                ('Prioridad', models.CharField(db_column='Prioridad', default='Prioridad', max_length=25)),
            ],
            options={
                'db_table': 'Prioridad',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idStatus', models.AutoField(db_column='idStatus', primary_key=True, serialize=False)),
                ('Status', models.CharField(db_column='Status', default='Status', max_length=15)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('idTarea', models.AutoField(db_column='idTarea', primary_key=True, serialize=False)),
                ('Titulo', models.CharField(db_column='Titulo', default='Titulo', max_length=50)),
                ('Descripcion', models.CharField(db_column='Descripcion', default='Descripcion', max_length=200)),
                ('Fecha_inicio', models.DateTimeField(db_column='Fecha_creacion', default='2000-01-01 12:00')),
                ('Fecha_termino', models.DateTimeField(db_column='Fecha_vencimiento', default='2000-01-01 12:00')),
                ('fk_Prioridad', models.ForeignKey(db_column='fk_Prioridad', on_delete=django.db.models.deletion.CASCADE, to='api.prioridad')),
                ('fk_Status', models.ForeignKey(db_column='fk_Status', on_delete=django.db.models.deletion.CASCADE, to='api.status')),
                ('fk_Usuario', models.ForeignKey(db_column='fk_Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tareas',
            },
        ),
        migrations.CreateModel(
            name='Tareas_has_etiquetas',
            fields=[
                ('idTareas_has_etiquetas', models.AutoField(db_column='idTareas_has_etiquetas', default=1, primary_key=True, serialize=False)),
                ('fk_Etiqueta', models.ForeignKey(db_column='fk_Etiqueta', on_delete=django.db.models.deletion.CASCADE, to='api.etiquetas')),
                ('fk_Tarea', models.ForeignKey(db_column='fk_Tarea', on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
            options={
                'db_table': 'Tareas_has_etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Listas_has_tareas',
            fields=[
                ('idListas_has_tareas', models.AutoField(db_column='idListas_has_tareas', default=1, primary_key=True, serialize=False)),
                ('fk_Lista', models.ForeignKey(db_column='fk_Lista', on_delete=django.db.models.deletion.CASCADE, to='api.lista_tareas')),
                ('fk_Tarea', models.ForeignKey(db_column='fk_Tarea', on_delete=django.db.models.deletion.CASCADE, to='api.tareas')),
            ],
            options={
                'db_table': 'Listas_has_tareas',
            },
        ),
    ]
